// @flow

export const ADD_NEW_TASK = 'ADD_NEW_TASK',
  DELETE_TASK = 'DELETE_TASK',
  MERGE_STATE = 'MERGE_STATE',
  SET_ACTIVE_DATE = 'SET_ACTIVE_DATE',
  SET_ACTIVE_MONTH = 'SET_ACTIVE_MONTH',
  SORT_TASKS = 'SORT_TASKS',
  UPDATE_TASK = 'UPDATE_TASK'
