// flow-typed signature: 11b8931cd764242a95217f0a3dd11f18
// flow-typed version: <<STUB>>/styled-jsx-plugin-postcss_v^0.1.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-jsx-plugin-postcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-jsx-plugin-postcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-jsx-plugin-postcss/processor' {
  declare module.exports: any;
}

declare module 'styled-jsx-plugin-postcss/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-jsx-plugin-postcss/index' {
  declare module.exports: $Exports<'styled-jsx-plugin-postcss'>;
}
declare module 'styled-jsx-plugin-postcss/index.js' {
  declare module.exports: $Exports<'styled-jsx-plugin-postcss'>;
}
declare module 'styled-jsx-plugin-postcss/processor.js' {
  declare module.exports: $Exports<'styled-jsx-plugin-postcss/processor'>;
}
declare module 'styled-jsx-plugin-postcss/test.js' {
  declare module.exports: $Exports<'styled-jsx-plugin-postcss/test'>;
}
